import { mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, vi } from 'vitest';
import {
  type RegistryFile,
  documentKeyFromVfsKey,
  renderDocumentsRegistry,
} from '../src/codegen/documents_registry.js';

describe('documentKeyFromVfsKey', () => {
  it('strips the _types suffix', () => {
    expect(documentKeyFromVfsKey('researches/writing_types')).toBe('researches/writing');
    expect(documentKeyFromVfsKey('post_types')).toBe('post');
  });

  it('keeps keys without the suffix untouched', () => {
    expect(documentKeyFromVfsKey('researches/writing')).toBe('researches/writing');
  });
});

describe('renderDocumentsRegistry', () => {
  const files: RegistryFile[] = [
    {
      vfsKey: 'researches/writing_types',
      importPath: '../../app/collaboration/documents/researches/writing_types',
    },
    { vfsKey: 'blog/post_types', importPath: '../../app/collaboration/documents/blog/post_types' },
  ];

  it('emits a quoted type-map keyed by document name', () => {
    const lines = renderDocumentsRegistry(files);
    const content = lines.join('\n');

    expect(content).toContain(
      "'researches/writing': typeof import('../../app/collaboration/documents/researches/writing_types');",
    );
    expect(content).toContain(
      "'blog/post': typeof import('../../app/collaboration/documents/blog/post_types');",
    );
    expect(content).toContain('export type CollabDocumentName = keyof CollabDocumentModules;');
  });

  it('marks the file as generated', () => {
    const content = renderDocumentsRegistry(files).join('\n');
    expect(content).toContain('Generated by @adonis-agora/collaboration — do not edit.');
  });

  it('renders an empty registry as CollabDocumentName = never', () => {
    const content = renderDocumentsRegistry([]).join('\n');
    expect(content).toContain('export type CollabDocumentName = never;');
    expect(content).not.toContain('typeof import');
  });

  it('deduplicates repeated keys', () => {
    const duplicated = [...files, files[0]!];
    const content = renderDocumentsRegistry(duplicated).join('\n');
    expect(content.match(/typeof import\(/g)).toHaveLength(2);
  });
});

describe('codegen_init hook', async () => {
  const hookModule = await import('../src/codegen_init.js');
  type InitFn = (
    parent: unknown,
    hooksManager: unknown,
    indexGenerator: { add(name: string, config: Record<string, unknown>): unknown },
  ) => void;
  const initFn = hookModule.default as InitFn;

  const originalCwd = process.cwd();
  let fixtureWithDir: string;
  let fixtureWithoutDir: string;

  function fakeIndexGenerator() {
    const calls: Array<{ name: string; config: Record<string, unknown> }> = [];
    return {
      calls,
      add(name: string, config: Record<string, unknown>) {
        calls.push({ name, config });
        return this;
      },
    };
  }

  beforeAll(() => {
    // Fixture WITH the documents directory.
    fixtureWithDir = path.join(tmpdir(), `collab-hook-with-${Date.now()}`);
    mkdirSync(path.join(fixtureWithDir, 'app', 'collaboration', 'documents'), {
      recursive: true,
    });

    // Fixture WITHOUT it.
    fixtureWithoutDir = path.join(tmpdir(), `collab-hook-without-${Date.now()}`);
    mkdirSync(fixtureWithoutDir, { recursive: true });
  });

  afterAll(() => {
    process.chdir(originalCwd);
    rmSync(fixtureWithDir, { recursive: true, force: true });
    rmSync(fixtureWithoutDir, { recursive: true, force: true });
  });

  it('registers the collabDocuments IndexGenerator source when the dir exists', () => {
    process.chdir(fixtureWithDir);
    const generator = fakeIndexGenerator();
    initFn(undefined, undefined, generator);

    expect(generator.calls).toHaveLength(1);
    const { name, config } = generator.calls[0]!;
    expect(name).toBe('collabDocuments');
    expect(config.source).toBe('./app/collaboration/documents');
    expect(config.output).toBe('./.adonisjs/collaboration/documents.ts');
    expect(typeof config.as).toBe('function');
  });

  it('custom `as` renders vfs entries through the renderer into the buffer', () => {
    process.chdir(fixtureWithDir);
    const generator = fakeIndexGenerator();
    initFn(undefined, undefined, generator);

    const writtenLines: string[] = [];
    const fakeBuffer = {
      writeLine(line: string) {
        writtenLines.push(line);
        return this;
      },
    };
    const fakeVfs = {
      asList: () => ({ writing_types: '/abs/app/collaboration/documents/writing_types.ts' }),
    };

    const config = generator.calls[0]!.config as {
      as: (vfs: unknown, buffer: unknown, c: unknown, h: unknown) => void;
    };
    config.as(fakeVfs, fakeBuffer, {}, { toImportPath: (p: string) => p });

    expect(writtenLines.join('\n')).toContain("'writing'");
  });

  it('skips registration when the documents directory does not exist', () => {
    process.chdir(fixtureWithoutDir);
    const add = vi.fn();
    initFn(undefined, undefined, { add });
    expect(add).not.toHaveBeenCalled();
  });
});
