/**
 * Core types of the collaboration library.
 *
 * The abstraction is document-first: a `CollabDocument` is identified by name
 * (`researches/<id>/writing`, for example) and the chosen driver decides how
 * to sync (Yjs/Hocuspocus or Automerge). Everything engine-specific stays
 * behind the interfaces — the app only consumes `CollaborationManager`.
 */

/**
 * Underlying CRDT engine.
 *
 * `partykit` runs the sync on edge (Cloudflare Workers + Durable Objects) on
 * an origin separate from Adonis — WebSocket traffic doesn't go through the
 * Node server.
 */
export type CollaborationEngine = 'yjs' | 'automerge' | 'partykit' | 'partyserver';

/**
 * Edge sync config (engine `partykit`). The worker is generated by
 * `node ace collaboration:init --engine=partykit` and deployed separately;
 * the driver talks to it via HTTP (`onRequest`).
 */
export interface PartyKitConfig {
  /** PartyKit deployment host (e.g. 'my-app.partykit.dev' or localhost:1999). */
  roomHost: string;
  /** Party name on the worker (default 'main'). */
  party?: string;
  /**
   * HS256 secret used to issue/validate the ephemeral JWT exchanged between
   * Adonis, browser and worker. Required in production — without it the
   * worker rejects connections when configured with `requireToken`.
   */
  jwtSecret?: string;
  /** Timeout for HTTP calls to the worker, in ms (default 10000). */
  fetchTimeoutMs?: number;
}

/**
 * Anchor of a comment — generic over content type.
 * The library persists the anchor + lifecycle; interpreting it is up to the
 * resolver registered by the app (text → offsets, canvas → shapeId, media → timestamp).
 */
export type CommentAnchor =
  | { kind: 'text-range'; start: number; end: number; selectedText: string }
  | { kind: 'canvas-object'; shapeId: string; relativeX: number; relativeY: number }
  | { kind: 'timestamp'; at: number; end?: number };

/** Comment persisted by the library (thread + resolved + author). */
export interface CollabComment {
  id: string;
  documentName: string;
  /** Document space where the anchor lives ('text', 'canvas', ...). */
  space: string;
  anchor: CommentAnchor;
  body: string;
  userId: string;
  authorName?: string | null;
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string | null;
}

/** Authentication payload attached to the WebSocket connection. */
export interface CollabConnectionContext {
  /** Id of the authenticated user (the provider validates before the handshake). */
  userId: string;
  /** Free-form metadata (name, avatar) for presence. */
  user?: { name?: string; avatarUrl?: string | null };
}

/** Result of read/write authorization for a document. */
export interface CollabPermission {
  canRead: boolean;
  /** Write to the document content (central editor). */
  canWrite: boolean;
  /** Comment (side annotations — doesn't change the text). */
  canComment: boolean;
}

/** Collaborative document loaded by the driver. */
export interface LoadedCollabDocument {
  /** Full binary state to send to a new client (merge update). */
  state: Uint8Array;
  /** State vector for differential sync (Yjs: state vector; Automerge: heads). */
  vector: Uint8Array;
}

/** A version registered in the document history. */
export interface CollabVersion {
  /** Opaque reference for the driver (Yjs snapshot / Automerge hash). */
  id: string;
  createdAt: string;
  createdBy: string | null;
  label: string | null;
  /** Friendly sequential number (1, 2, 3...). */
  seq: number;
}

/** Diff statistics between two versions. */
export interface CollabDiffSummary {
  added: number;
  removed: number;
}

/**
 * Persistence of documents + versions + comments. The host app implements
 * this (database, S3...) and the library only knows the interface.
 */
export interface CollaborationStorage {
  loadDocument(docName: string): Promise<{ state: Uint8Array } | null>;
  saveDocument(docName: string, state: Uint8Array, meta?: Record<string, unknown>): Promise<void>;
  listVersions(docName: string): Promise<CollabVersion[]>;
  saveVersion(docName: string, version: CollabVersion, snapshot: Uint8Array): Promise<void>;
  loadVersionSnapshot(docName: string, versionId: string): Promise<Uint8Array | null>;
  /** Comments of a document (by space). */
  listComments(docName: string, space?: string): Promise<CollabComment[]>;
  saveComment(docName: string, comment: CollabComment): Promise<void>;
  deleteComment(docName: string, commentId: string): Promise<void>;
}

/** Manager configuration. */
export interface CollaborationConfig {
  engine: CollaborationEngine;
  /** Omitted = in-memory (dev only). The config stub publishes a default. */
  storage?: CollaborationStorage;
  /**
   * Per-document authorization. Called at the handshake (onAuthenticate) and
   * on every relevant permission change — return false to drop the connection.
   */
  authorize: (ctx: CollabConnectionContext, docName: string) => Promise<CollabPermission>;
  /** Redis for cross-instance presence (optional in single-instance dev). */
  redis?: { url: string };
  /** Edge sync via PartyKit (required when engine = 'partykit'). */
  partykit?: PartyKitConfig;
  /** WS port/path when embedded in the Adonis HTTP server. */
  path?: string;
  /** Persistence debounce in ms (default 2000). */
  debounce?: number;
}
