/**
 * Core types of the collaboration library.
 *
 * The abstraction is document-first: a `CollabDocument` is identified by name
 * (`researches/<id>/writing`, for example) and the chosen driver decides how
 * to sync (Yjs/Hocuspocus or Automerge). Everything engine-specific stays
 * behind the interfaces — the app only consumes `CollaborationManager`.
 */

/**
 * Underlying CRDT engine.
 *
 * `partykit` runs the sync on edge (Cloudflare Workers + Durable Objects) on
 * an origin separate from Adonis — WebSocket traffic doesn't go through the
 * Node server.
 */
export type CollaborationEngine = 'yjs' | 'automerge' | 'partykit' | 'partyserver';

/**
 * Edge sync config (engine `partykit`). The worker is generated by
 * `node ace collaboration:init --engine=partykit` and deployed separately;
 * the driver talks to it via HTTP (`onRequest`).
 */
export interface PartyKitConfig {
  /** PartyKit deployment host (e.g. 'my-app.partykit.dev' or localhost:1999). */
  roomHost: string;
  /** Party name on the worker (default 'main'). */
  party?: string;
  /**
   * HS256 secret used to issue/validate the ephemeral JWT exchanged between
   * Adonis, browser and worker. Required in production — without it the
   * worker rejects connections when configured with `requireToken`.
   */
  jwtSecret?: string;
  /** Timeout for HTTP calls to the worker, in ms (default 10000). */
  fetchTimeoutMs?: number;
}

/**
 * Anchor of a comment — generic over content type.
 * The library persists the anchor + lifecycle; interpreting it is up to the
 * resolver registered by the app (text → offsets, canvas → shapeId, media → timestamp).
 */
export type CommentAnchor =
  | { kind: 'text-range'; start: number; end: number; selectedText: string }
  | { kind: 'canvas-object'; shapeId: string; relativeX: number; relativeY: number }
  | { kind: 'timestamp'; at: number; end?: number };

/** Comment persisted by the library (thread + resolved + author). */
export interface CollabComment {
  id: string;
  documentName: string;
  /** Document space where the anchor lives ('text', 'canvas', ...). */
  space: string;
  anchor: CommentAnchor;
  body: string;
  userId: string;
  authorName?: string | null;
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string | null;
}

/** Authentication payload attached to the WebSocket connection. */
export interface CollabConnectionContext {
  /** Id of the authenticated user (the provider validates before the handshake). */
  userId: string;
  /** Free-form metadata (name, avatar) for presence. */
  user?: { name?: string; avatarUrl?: string | null };
}

/** Result of read/write authorization for a document. */
export interface CollabPermission {
  canRead: boolean;
  /** Write to the document content (central editor). */
  canWrite: boolean;
  /** Comment (side annotations — doesn't change the text). */
  canComment: boolean;
}

/** Collaborative document loaded by the driver. */
export interface LoadedCollabDocument {
  /** Full binary state to send to a new client (merge update). */
  state: Uint8Array;
  /** State vector for differential sync (Yjs: state vector; Automerge: heads). */
  vector: Uint8Array;
}

/**
 * Why {@link CollaborationManager.withLiveDocument} had no document to run on.
 *
 * The two are different operational facts and a caller that cannot tell them
 * apart writes the wrong fallback: `not-loaded` is normal and temporary (open
 * the document, or fall back to `getDocumentState`), while
 * `engine-has-no-live-document` never changes for that document and means the
 * whole approach is wrong for it.
 */
export type LiveDocumentAbsence =
  /** The engine keeps documents in this process, but nobody has this one open here. */
  | 'not-loaded'
  /** The engine syncs elsewhere (PartyKit, on the edge): there is no in-process instance. */
  | 'engine-has-no-live-document';

/**
 * Outcome of {@link CollaborationManager.withLiveDocument} — what the callback
 * returned, or why it never ran.
 *
 * A result, not an exception and not a bare `undefined`: "there is no live
 * document" is an ordinary answer here (nobody has the document open), and a
 * `T | undefined` would collapse it into a callback that legitimately returned
 * `undefined`.
 */
export type LiveDocumentResult<T> =
  | { live: true; value: T }
  | { live: false; value?: undefined; reason: LiveDocumentAbsence };

/** A version registered in the document history. */
export interface CollabVersion {
  /** Opaque reference for the driver (Yjs snapshot / Automerge hash). */
  id: string;
  createdAt: string;
  createdBy: string | null;
  label: string | null;
  /** Friendly sequential number (1, 2, 3...). */
  seq: number;
}

/** Diff statistics between two versions. */
export interface CollabDiffSummary {
  added: number;
  removed: number;
}

/** Options of {@link CollaborationStorage.pruneVersions}. */
export interface PruneVersionsOptions {
  /**
   * How many versions to keep **per document**. A busy document never evicts
   * another document's history. `0` deletes every version.
   */
  keep: number;
  /** Narrows the prune to a single document. Omitted prunes every document. */
  docName?: string;
  /** Count what would be removed without deleting anything. */
  dryRun?: boolean;
}

/**
 * Persistence of documents + versions + comments. The host app implements
 * this (database, S3...) and the library only knows the interface.
 */
export interface CollaborationStorage {
  loadDocument(docName: string): Promise<{ state: Uint8Array } | null>;
  saveDocument(docName: string, state: Uint8Array, meta?: Record<string, unknown>): Promise<void>;
  listVersions(docName: string): Promise<CollabVersion[]>;
  saveVersion(docName: string, version: CollabVersion, snapshot: Uint8Array): Promise<void>;
  loadVersionSnapshot(docName: string, versionId: string): Promise<Uint8Array | null>;
  /**
   * Delete all but the `keep` most recent versions, per document. Returns how
   * many versions were removed (or would be, with `dryRun`).
   */
  pruneVersions(options: PruneVersionsOptions): Promise<number>;
  /** Comments of a document (by space). */
  listComments(docName: string, space?: string): Promise<CollabComment[]>;
  /**
   * One comment by id. Optional: a storage that cannot look one up directly is
   * served by {@link CommentService.get} falling back to a filtered list — the
   * point of the hook is that a backend WITH an index (Lucid) does not have to
   * load every comment on a document to authorize a PATCH.
   */
  getComment?(docName: string, commentId: string): Promise<CollabComment | null>;
  saveComment(docName: string, comment: CollabComment): Promise<void>;
  deleteComment(docName: string, commentId: string): Promise<void>;
}

/** Manager configuration. */
export interface CollaborationConfig {
  engine: CollaborationEngine;
  /**
   * Optional per-document engine resolution. When provided, documents are
   * routed to the driver of their resolved engine; `engine` stays the
   * fallback for docs the resolver does not special-case.
   */
  engineFor?: (docName: string) => CollaborationEngine | Promise<CollaborationEngine>;
  /**
   * Declarative documents: structured patterns that resolve engine and
   * authorize per document type (see {@link CollabDocumentDeclaration}).
   * Optional — plain `engine` + `authorize` remain the fallback.
   */
  // biome-ignore lint/suspicious/noExplicitAny: params are per-entry — a concrete Record<string, string> would reject defineDocument<{ id: string }>
  documents?: Record<string, import('./documents.js').CollabDocumentDeclaration<any>>;
  /** Omitted = in-memory (dev only). The config stub publishes a default. */
  storage?: CollaborationStorage;
  /**
   * Global per-document authorization. May be omitted when `documents`
   * declares authorize for every type — unmatched docs then fall back to
   * deny.
   *
   * **Evaluated once per connection**, at the handshake (`onAuthenticate`),
   * and once per REST request. Nothing re-runs it afterwards: revoking a
   * user's access does NOT drop the socket they already hold, and they keep
   * syncing that document until they disconnect. When a revocation has to
   * take effect immediately, close the connection from the app side (or
   * restart the document) — the rule alone will not do it.
   */
  authorize?: (ctx: CollabConnectionContext, docName: string) => Promise<CollabPermission>;
  /**
   * Key that signs and verifies the self-hosted collaboration token.
   *
   * Optional because an AdonisJS app already has one: with nothing set here
   * the library derives its key from the app's `appKey`, so the secure path
   * is the path that requires no configuration. Set it to use a dedicated
   * key, or when embedding the manager outside an Adonis app — a manager with
   * neither refuses to issue or accept tokens rather than falling back to an
   * unsigned format.
   *
   * Rotating it invalidates every outstanding token. Clients reconnect and
   * fetch a new one, so the visible cost is one reconnect.
   */
  tokenSecret?: string;
  /** Redis for cross-instance presence (optional in single-instance dev). */
  redis?: { url: string };
  /** Edge sync via PartyKit (required when engine = 'partykit'). */
  partykit?: PartyKitConfig;
  /** WS port/path when embedded in the Adonis HTTP server. */
  path?: string;
  /** Persistence debounce in ms (default 2000). */
  debounce?: number;
}
