/**
 * Renderer for the collaborative-documents registry generated at
 * `.adonisjs/collaboration/documents.ts` by the Assembler `init` hook.
 *
 * Pure function so it is trivially testable — the hook only adapts
 * vfs/buffer and delegates here.
 */

/** File discovered by the IndexGenerator. */
export interface RegistryFile {
  /** Extension-less relative key from the vfs (e.g. 'researches/writing_types'). */
  vfsKey: string;
  /** Import path already resolved via helpers.toImportPath. */
  importPath: string;
}

/**
 * Converts a vfs key into a document name — same convention as
 * `make:collab-document`: the '_types' suffix is stripped.
 *
 *   'researches/writing_types' -> 'researches/writing'
 */
export function documentKeyFromVfsKey(vfsKey: string): string {
  return vfsKey.replace(/_types$/, '');
}

/**
 * Renders the typed registry lines. The map is type-only (`typeof import`),
 * so the file produces no runtime code — consumed by tsc and re-exportable
 * to the frontend through manifest/config types.
 */
export function renderDocumentsRegistry(files: RegistryFile[]): string[] {
  const seen = new Set<string>();
  const unique = files.filter((file) => {
    const key = documentKeyFromVfsKey(file.vfsKey);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  const lines: string[] = [
    '/**',
    ' * Generated by @adonis-agora/collaboration — do not edit.',
    ' * Refresh with `node ace codegen`.',
    ' */',
  ];

  if (unique.length === 0) {
    lines.push(
      '',
      '/** No collaborative documents declared yet. Use `node ace make:collab-document`. */',
      'export type CollabDocumentName = never;',
      '',
      'export type CollabDocumentDefinition<Name extends CollabDocumentName> = Name extends never',
      '  ? never',
      '  : unknown;',
    );
    return lines;
  }

  lines.push('', 'type CollabDocumentModules = {');
  for (const file of unique) {
    const key = documentKeyFromVfsKey(file.vfsKey);
    // Always quote — doc names may contain slashes/hyphens.
    lines.push(`  '${key}': typeof import('${file.importPath}');`);
  }
  lines.push(
    '};',
    '',
    '/** Valid collaborative document names in this app. */',
    'export type CollabDocumentName = keyof CollabDocumentModules;',
    '',
    '/** Document definition module (the *_types default export). */',
    'export type CollabDocumentDefinition<Name extends CollabDocumentName> =',
    '  CollabDocumentModules[Name][',
    "'default'",
    '];',
  );

  return lines;
}
