import { BaseCommand, args, flags } from '@adonisjs/core/ace';
import stringHelpers from '@adonisjs/core/helpers/string';
import { stubsRoot } from '../stubs/main.js';

/**
 * `node ace make:collab-document researches/writing`
 *
 * Generates the shared types for a collaborative document (doc name
 * pattern, spaces, allowed anchor kinds) at
 * `app/collaboration/documents/<name>_types.ts`. The typed registry in
 * `.adonisjs/collaboration/documents.ts` is refreshed automatically by the
 * codegen hook (`node ace codegen` / dev server).
 */
export default class MakeCollabDocument extends BaseCommand {
  static override commandName = 'make:collab-document';
  static override description = 'Make shared types for a collaborative document (spaces + anchors)';
  static override options = { startApp: true, allowUnknownFlags: true };

  @args.string({ description: 'Collaborative document name (e.g. researches/writing)' })
  declare name: string;

  @flags.string({
    description:
      'Allowed anchor kinds as a comma-separated list (text-range,canvas-object,timestamp)',
  })
  declare anchors?: string;

  @flags.string({ description: "Document spaces as a comma-separated list (default 'text')" })
  declare spaces?: string;

  override async run(): Promise<void> {
    const entity = this.app.generators.createEntity(this.name);
    const documentName = `${entity.path ? `${entity.path}/` : ''}${stringHelpers.snakeCase(entity.name)}`;
    const className = stringHelpers.pascalCase(entity.name);
    const fileName = `${stringHelpers.snakeCase(entity.name)}_types.ts`;

    const anchorKinds = (this.anchors ?? 'text-range')
      .split(',')
      .map((kind) => kind.trim())
      .filter((kind) => ['text-range', 'canvas-object', 'timestamp'].includes(kind));
    if (anchorKinds.length === 0) {
      this.logger.error('invalid --anchors. Use values from: text-range, canvas-object, timestamp');
      this.exitCode = 1;
      return;
    }

    const spaceList = (this.spaces ?? 'text')
      .split(',')
      .map((space) => space.trim())
      .filter(Boolean);

    const codemods = await this.createCodemods();
    await codemods.makeUsingStub(stubsRoot, 'collaboration/document_types.stub', {
      document: {
        documentName,
        className,
        fileName,
        anchorKinds,
        spaceList,
      },
    });
    this.logger.action(`create app/collaboration/documents/${fileName}`).succeeded();

    // The typed registry is generated by the codegen init hook scanning
    // app/collaboration/documents — nothing to edit by hand.
    this.logger.info(
      [
        '',
        `Document '${documentName}' registered. Refresh the typed registry with:`,
        '  node ace codegen   (or restart the dev server)',
        '→ importable from .adonisjs/collaboration/documents.ts',
        '  (types CollabDocumentName / CollabDocumentDefinition)',
        '',
      ].join('\n'),
    );
  }
}
